

services:
  db:
    image: mysql
    restart: always
    # ports:
    #   - 8081:8081
    environment:
      MYSQL_ROOT_PASSWORD: FridgeGoo323#
      MYSQL_USER: root
      MYSQL_PASSWORD: FridgeGoo323#
      MYSQL_DATABASE: wiz_blog_db
      

  node_api:
    # build: .
    image: blog_mysql_node
    ports:
      - 3000:8080