

services:
  db:
    image: mysql
    restart: always
    # ports:
    #   - "3307:8080"
    environment:
      MYSQL_ROOT_PASSWORD: FridgeGoo323#
      MYSQL_DATABASE: wiz_blog_db
      # MYSQL_USER: root
      # MYSQL_PASSWORD: FridgeGoo323#
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nodejs-mysql-network
  node_api:
    build: .
    # dockerfile: Dockerfile
    # image: blog_mysql_node
    ports:
      - 8080:8081
    environment:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASSWORD: FridgeGoo323#
      DB_NAME: wiz_blog_db
      DB_PORT: 3306
    depends_on:
      - db
volumes:
  mysql-data:
networks:
  nodejs-mysql-network:
    name: nodejs-mysql-network