
services:
  db:
    image: mysql
    restart: always
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      # MYSQL_USER: 
      # MYSQL_PASSWORD: 
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nodejs-mysql-network
  node_api:
    build: .
    # dockerfile: Dockerfile
    # image: blog_mysql_node
    ports:
      - 8080:8081
    environment:
      DB_HOST: 
      DB_USER: 
      DB_PASSWORD: 
      DB_NAME: 
      DB_PORT: 
    depends_on:
      - db
volumes:
  mysql-data:
networks:
  nodejs-mysql-network:
    name: nodejs-mysql-network
    