

services:
  mongo_db:
    image: mongo:latest
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: HarkTheChosen
      ME_CONFIG_MONGODB_ADMINPASSWORD: NotPasswordDerp
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_MONGODB_URL: mongodb+srv://HarkTheChosen:NotPasswordDerp@cluster0.stpbjuq.mongodb.net/myBlog?retryWrites=true&w=majority
      ME_CONFIG_BASICAUTH: false

  node_api:
    build: .
    ports:
      - 8080:8080